# Generated by Django 3.2.5 on 2021-07-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(db_column='role_number', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('address', models.TextField(db_column='addrress')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(db_column='sub_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='subject_name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.FloatField(db_column='marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.subject')),
            ],
        ),
    ]
